sudo: required
language: bash
services: docker

dist: trusty

env:
  - VERSION=latest
  - VERSION=9.6-2.3
  - VERSION=9.5-2.3
  - VERSION=sig
  - VERSION=9.4-2.3
  - VERSION=9.3-2.3

before_install:
  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="tmanubrio/postgis:$VERSION"

script:
  - docker build --pull -t "$image" .

deploy:
  provider: script
  script:
    # push to dockerhub
    docker push "$image";
  branch: master